name: Test API
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install curl
        run: sudo apt update && sudo apt install curl -y
      - name: Run temp.sh
        run: bash temp.sh
